name: _load
on:
  workflow_call:
    inputs:
      site:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
         required: true
    # secrets:
    #   APP_ID:
    #     required: true
    #   APP_PRIVATE_KEY:
    #     required: true
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run api:load
      # - uses: tibdex/github-app-token@v1
      #   if: ${{ !env.ACT }}
      #   id: create-ffmpeg-token
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: FedericoCarboni/setup-ffmpeg@v2
        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
          token: ${{ secrets.GITHUB_TOKEN }}
          # with:
          #   token: ${{ steps.create-ffmpeg-token.outputs.token }}
      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - name: Download data from API
        run: |
          mkdir -p scripts/data
          echo disabled curl -L -o scripts/data/channels.json https://raw.githubusercontent.com/tinuva/epg/main/scripts/data/channels.json
          curl -L -o scripts/data/input.json 'https://www.dstv.com/umbraco/api/TvGuide/GetChannels?country=zaf&unit=dstv'
          cat scripts/data/input.json  | jq -r '.Channels[] | {Number, id: .Tag, name: .Name, icon: .Logo}' | scripts/data/channels.json
          ls -lsah scripts/data
          echo '<?xml version="1.0"?>' > sites/dstv.com/dstv.com_za.channels.xml
          echo '<site site="dstv.com">' >> sites/dstv.com/dstv.com_za.channels.xml
          echo '<channels>' >> sites/dstv.com/dstv.com_za.channels.xml
          jq -r '.Channels[] | "<channel lang=\"en\" xmltv_id=\"\(.Tag)\" site_id=\"zaf#\(.Number)\">\(.Name)</channel>"' >> sites/dstv.com/dstv.com_za.channels.xml
          echo '</channels>' >> sites/dstv.com/dstv.com_za.channels.xml
          echo '</site>' >> sites/dstv.com/dstv.com_za.channels.xml
      - run: CHANNELS_PATH=sites/${{inputs.site}}/*.channels.xml npm run queue:create -- --max-clusters=1 --days=3
      - run: NODE_OPTIONS=--insecure-http-parser npm run cluster:load -- --timeout=30000  --cluster-id=1
      - run: npm run programs:save
      - run: npm run guides:update
      # - uses: tibdex/github-app-token@v1
      #   if: ${{ !env.ACT }}
      #   id: create-deploy-token
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: .gh-pages
          #token: ${{ steps.create-deploy-token.outputs.token }}
          #token: ${{ secrets.ACCESS_TOKEN }}
          git-config-name: iptv-bot[bot]
          git-config-email: 84861620+iptv-bot[bot]@users.noreply.github.com
          commit-message: '[Bot] Deploy to GitHub Pages'
          clean: false
